spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lovepets?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 162.14.71.2  #采用的服务器地址
    port: 6379      #采用的服务器端口
    password: 123456
    client-type: lettuce
    jedis:
      pool:
        max-active: 16


server:
  port: 81


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: tab_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
